### ISSUE TITLE
Prepare up-to-date road map for Kubescape project

### ISSUE THREAD

**Issue by slashben** [kubescape/project-governance#1]
Update the roadmap of the Kubescape project here in the governance repository based on the existing roadmaps

**Comment by matthyx** [comment]
@slashben the doc looks good, I don't see anything missing from the list we discussed earlier this year

**Comment by matthyx** [comment]
who's going to write it to markdown?

**Comment by slashben** [comment]
https://github.com/kubescape/project-governance/pull/21

**Comment by slashben** [comment]
need approval from @craigbox @dwertent @rotemamsa
