### ISSUE TITLE
Add "user getting started" links to Kubescape.io

### ISSUE THREAD

**Issue by slashben** [kubescape/project-governance#17]

**Comment by Oshratn** [comment]
@slashben sorry, I don't understand the task.

**Comment by slashben** [comment]
The idea was to send people from Kubescape.io to the "getting started"s (both as a new user or a new contributor) to Github (or keep them there, just have the information in place)

**Comment by Oshratn** [comment]
[PR #79 on kubescape.io resolves this.](https://github.com/kubescape/kubescape.io/pull/79)

**Comment by Oshratn** [comment]
@slashben / @matthyx
The **About** of the Kubescape needs to be updated to:

> Kubescape is an open-source Kubernetes security platform that provides comprehensive security coverage, from left to right across the entire development and deployment lifecycle. It offers hardening, posture management, and runtime security capabilities to ensure robust protection for Kubernetes environments.
