### ISSUE TITLE
Proposal for new maintainer in the project

### ISSUE THREAD

**Issue by slashben** [kubescape/project-governance#20]
I am proposing @amirmalka to be a maintainer in the project starting 2025

**Comment by craigbox** [comment]
SGTM.  Why not as of right now?

**Comment by slashben** [comment]
> SGTM. Why not as of right now?

As per the governance, we will vote for new maintainers in the quarterly meeting

**Comment by craigbox** [comment]
I don't think that's particularly practical, I'll vote to change the governance if needed 😁

**Comment by craigbox** [comment]
Welcome to Maintainer Club, Amir!
